### PR TITLE
Prolog

### PR DESCRIPTION
**Pull request by davidhbrown-uri**
Please do let me know if I should be doing something differently; hope this is a useful contribution.

### CODE REVIEW

**Comment by davidhbrown-uri** [comment]
ok to test

**Comment by anthonygego** [comment]
LGTM. However, as each Dockerfile command creates a new layer, cleaning would be much more effective if everything is done in one ``RUN`` command, replacing ``WORKDIR`` by ``cd``s and separating each sub- command using ``&&``. This would save a lot of space I think. You can escape new lines using ``\`` to keep the file clear. Can you test this and update your PR ?

Thanks.

**Comment by davidhbrown-uri** [comment]
Thank you very much, anthonygego for those suggestions; I really appreciate the help. I have reworked the Dockerfile to use a single RUN command and I was still able to build, enter the shell, and start the languages.

**Comment by anthonygego** [comment]
Thank you @davidhbrown-uri for this contribution.

**Pull request merged**
