### PR TITLE
cpp: Add gdb

### PR DESCRIPTION
**Pull request by oliviertilmans**
Adding gdb would let us provide backtrace when student's code crashes through the coredump file.

### CODE REVIEW

**Comment by oliviertilmans** [comment]
ok to test

**Comment by oliviertilmans** [comment]
@anthonygego Any chances to get this merged ?

**Comment by GuillaumeDerval** [comment]
Yes I'll merge this today and update our instance :-)

(Anthony told me that you also need to access core dumps made by the kernel; I don't think that's possible for now with docker, althought there are discussions (see docker/docker#19289))

**Comment by oliviertilmans** [comment]
If the ssh instance is an actual container, then it apparently generates the core dumps in the current directory.

**Comment by GuillaumeDerval** [comment]
It is either non-documented by Docker or system-specific...

My opinion is that it is indeed system-specific and the ABRT daemon on our CentOS host does some magic.

The general advice is that nobody should rely on this as it can change without notice...

(however, on our instance, you can for now use this fact as it's not going to change anytime soon... but I said nothing)

**Comment by oliviertilmans** [comment]
I found a way by using a LD_PRELOAD hook with libSegFault (and linking with -rdynamic).
However the log is cluttered with the status of every register and linked *.so
As long as it works, the gdb approach should be more readable

**Pull request merged**
