### PR TITLE
Container for improved feedback (Master Thesis)

### PR DESCRIPTION
**Pull request by zorga**
This is a Dockerfile for building my container taking the cpp image as base. I need it, in the context of my master thesis, to be able to test an exercise for Olivier Bonaventure's SINF1252 course.
The two other files are necessary to build an extended feedback on the C exercises :
The HTML file is a template page to display the improved feedback.
The key file is a private key only used to copy files from the container during the grading, on a web server located on the INGI network.

### CODE REVIEW

**Comment by zorga** [comment]
test this please

**Comment by zorga** [comment]
ok to test

**Comment by GuillaumeDerval** [comment]
We are not going to add this PR to the official repo in its current state.

Some notes to make it accepted next time:

- You should _**never**_ put a private RSA key in a public (even private) repository. **Please withdraw this key as soon as possible** and regenerate another, that you will keep private.
- The simple fact of having to share a private key with your container makes me feel that the architecture of your work is insecure. You should probably put a notice describing why it is necessary.
- You should describe more precisely what this container does.
- You should provide a README.md with your container.

You have to understand that if we accept your PR, we, INGInious maintainers, accept to maintain it in the future; thus you'll have to be very convincing ;-)

If you want to test it on the INGI instance of INGInious, you can contact me by mail. However, for the purpose of your master's thesis, I think testing it on an instance of INGInious located on your computer is sufficient.

**Comment by zorga** [comment]
Hello, the private key is a temporary solution. This private key has been generated for the only purposes of copying file using scp, from the container to an apache server located on a virtual machine inside the INGI department. This VM has been created only for me to host images files and static web pages.
I really do understand that putting an RSA key in a public repository is totally insecure. I totally agree with that. But it is the only solution available for now. This key is never used for other purposes and the VM is only reachable from the INGI network. So it should not be a problem. 

The container is used to check C program and to build images representing the memory during the execution of the program on the computer. So, it's why I need Graphviz and the corresponding python library : pygraphviz. I will write a README as soon as possible.

I hope you understand the situation.

**Comment by GuillaumeDerval** [comment]
We cannot add "temporary solutions", that are, moreover, specific to your use of INGInious, with a VM that is short-lived and only accessible to a very specific set of users, on the official repositories of INGInious.

As I said earlier, please test it locally on your computer (feel free to send me an email if you have any problem concerning the configuration of INGInious). 

If you *really* need to test it on inginious.info.ucl.ac.be, you can either send me a mail with a justification of why this is necessary, or ask your promoter to send me one (promoters do not need justifications ;-) ).

**Comment by zorga** [comment]
Ok thank you :-)

I understand the situation.

**Comment by 31416r** [comment]
I can confirm that we really have to install the stuff of zorga on inginious.info.ucl.ac.be, and another requirement is that his container needs to have access to the network to scp towards his. I think it can be a good test for "special" ways to use INGInious.

Thanks for your help Guillaume.

**Pull request closed without merging**
