### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by Simon3**
Add scalacheck

### CODE REVIEW

**Comment by GuillaumeDerval** [comment]
Don't you want to add also Junit?

**Comment by Simon3** [comment]
Scalacheck was the most important actually, but yep better add JUnit at the same time. 
It should be ok now.

**Comment by GuillaumeDerval** [comment]
(I'm gonna play a bit with the configuration of Jenkins, so do not take care of the following messages :D)

**Comment by GuillaumeDerval** [comment]
@INGIniousBot test this please

**Comment by GuillaumeDerval** [comment]
@INGIniousBot test this please

**Comment by GuillaumeDerval** [comment]
@INGIniousBot ok to test

**Comment by GuillaumeDerval** [comment]
@INGIniousBot ok to test

**Comment by GuillaumeDerval** [comment]
Still making some tests with Jenkins ;-)

@INGIniousBot retest this please

**Pull request merged**
